name: first job
on:
  push:
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run command shell
        run: echo "run command shell"
        shell: bash  
